### PR TITLE
Add Dromaeo Test Suite for Servo's benchmarking.

### PR DESCRIPTION
**Pull request by JayNakrani**
1. Adds Dromaeo test suite to AWFY.  These tests are generated by [Makefile](https://github.com/jeresig/dromaeo/blob/master/Makefile#L24)
2. Adds supporting code 
   - **`htmlrunner.js`**: A JavaScript that measures the time taken for each test and sends the results to local webserver on slave.
   - **`flask_server.py`**: A script that brings up small web server to serve individual test files and receives the test results from browser.

Please read [README](https://github.com/dhananjay92/arewefastyet/blob/add-dromaeo/benchmarks/servo/dromaeo/README.md) file. It explains how to manually run individual tests with this modified test suite.

---

Pull for review. 
@jdm, @h4writer: Please give your opinion on this.

### CODE REVIEW

**Comment by JayNakrani** [comment]
### TODO
- [x] Move the webserver's port to a separate config file so that `executors` can also use it. Currently it's hard-coded. _Done._

**Comment by JayNakrani** [comment]
Oh, yes. Forgot to mention this.
So currently, I am thinking of running all the tests as one-browser-instance-per-test. Do we want to run all the tests in single instance or is it okay to run them all in different instances?
For reference, [dromaeo.com](http://dromaeo.com) runs each test in a separate iframe.

**Comment by h4writer** [comment]
Actually we already have a benchmark that can run dromaeo!
https://github.com/h4writer/arewefastyet/blob/master/slave/benchmarks_remote.py#L61

It serves dromaeo by proxy'ing the actual website, but intercepting some files adjusting where the result is send too. It is used by some of our slaves, but takes 15minutes to run. E.g. therefore only a few slaves run this.

(this is "-b remote.dromaeo" as flag to the "execute.py" file)

**Comment by JayNakrani** [comment]
Oh, I see. Just saw that part of the code. I must say, that is one hell of a hack! :+1: 
We will re-use that for Servo as well. Thanks!

Closing this for now.

**Pull request closed without merging**
